// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opduoxexdtexbxxnjyws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wZHVveGV4ZHRleGJ4eG5qeXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMTQ1NzMsImV4cCI6MjA4Njg5MDU3M30.3S5nVMCI9ZHSp-6cUHFJ2djOp9x_uKCpFKnpNAVG7_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});